### ISSUE TITLE
Admin and WC customer views: show store credit available

### ISSUE THREAD

**Issue by ramiabraham** [AffiliateWP/affiliatewp-store-credit#10]
Customer had a good idea for an enhancement:
1. Is there any way for administrator to view balance remaining of an affiliates store credit?
2. Is there anyway for an affiliate to see their balance without having to go through checkout?

The first could be added in a variety of ways, most practical may be in the edit_affiliate tab, possibly the list table as well?

The second view could be hooked into the WC account page and/or affwp affiliate dashboard, perhaps with an option to control visibility of both via a new affwp add-on tab.

(https://secure.helpscout.net/conversation/83199434/7956/)

**Comment by ryanduff** [comment]
Already added this in my version-- adds to default stats tab so affiliate can view. Also added box on edit affiliate screen so that admins can view. 

One thing not there in my version is in the list table view, but I've wanted to get that added. 

Will get this wrapped up once I clean up my version and merge everything in.

**Comment by ramiabraham** [comment]
NICE

**Comment by sumobi** [comment]
:+1: to this. Showing it in the affiliate area clearly would be a great addition.

**Comment by sumobi** [comment]
A shortcode would be handy too

**Comment by wordmaid** [comment]
A customer has asked about this as a feature (seeing their balance) - I agree the affiliate area would be good, as well as a shortcode.

**Comment by ramiabraham** [comment]
For `[2.1.0](https://github.com/AffiliateWP/affiliatewp-store-credit/tree/release/2.1)`:

- Show store credit value in the dashboard, in the `statistics` tab.
- `[store_credit]` shortcode which displays current store credit available. `affiliate` parameter will get store credit for that affiliate. Falls back to currently logged-in user if `affiliate` parameter not specified.
- Show in _Edit Affiliate_ admin screen as non-editable input value.

**Comment by pippinsplugins** [comment]
Make that shortcode `[affiliate_store_credit]` please.

**Comment by michaelbeil** [comment]
Another request here: https://secure.helpscout.net/conversation/213249537/35976/?folderId=205529

**Comment by sumobi** [comment]
Another request https://secure.helpscout.net/conversation/265654527/44944/?folderId=205529. Would be great to get this implemented as soon as we are able to :)

**Comment by sumobi** [comment]
https://secure.helpscout.net/conversation/299517354/50120/?folderId=205531

**Comment by gspice** [comment]
Another request to view in the affiliate area, customer assumed it would be and is reporting it on a support ticket :-) 
https://secure.helpscout.net/conversation/338019385/55871/?folderId=205524

**Comment by gspice** [comment]
We so need this:
https://secure.helpscout.net/conversation/435944141/67149/?folderId=205529

Currently to view you need to query the database:

```
select * from wp_usermeta where meta_key = 'affwp_wc_credit_balance'
```

**Comment by amdrew** [comment]
https://secure.helpscout.net/conversation/464106516/70060?folderId=634609

**Comment by lisag** [comment]
https://secure.helpscout.net/conversation/459887525/69648?folderId=205529

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/93484827/9806?folderId=634609

**Comment by gspice** [comment]
Another:
https://secure.helpscout.net/conversation/489569259/72674?folderId=205524

**Comment by michaelbeil** [comment]
Ticket: https://secure.helpscout.net/conversation/525278507/76325?folderId=205529.

**Comment by amdrew** [comment]
Let's get this finished up.

An `Available Store Credit` section was added in v2.1 to the **Statistics** tab. This 
could potentially be moved to its own tab in a future version (and Affiliate Area Tabs could then allow it to be hidden) but for now I think it's fine where it is:

<img width="861" alt="screen shot 2018-02-20 at 6 31 17 pm" src="https://user-images.githubusercontent.com/52581/36408783-60504a0c-166c-11e8-9c40-3affb99212f1.png">

___

What's left for this issue, as discussed above:

- [ ] Add a `[affiliate_store_credit]` shortcode
- [ ] Show store credit on edit affiliate screen in admin
- [ ] Add store credit column to main affiliates screen in admin

**Comment by amdrew** [comment]
@gspice @michaelbeil The `[affiliate_store_credit]` shortcode is ready for testing.

Suggested above (https://github.com/AffiliateWP/affiliatewp-store-credit/issues/10#issuecomment-218237119) is an `affiliate` argument for the shortcode. I'm struggling to think of a use-case where the admin would want to show another affiliate's store credit balance on the site, other than to the affiliate who is currently logged in. Can anyone think of a reason to include this? Otherwise I think the standard shortcode should suffice.

Also, as noted in https://github.com/AffiliateWP/affiliatewp-store-credit/issues/10#issuecomment-366872255 there's a table that is shown (WooCommerce integration only) on the statistics tab of the Affiliate Area. It's likely we all missed this since there was a bug in how the affiliate's store credit balance was retrieved (https://github.com/AffiliateWP/affiliatewp-store-credit/issues/57). Would be great to get that tested also.

**Comment by amdrew** [comment]
The store credit shown on the edit affiliate screen. I decided to use a header and divider to section it off a bit from the other settings. Other add-ons such as Direct Link Tracking also do this, and there might be more settings added in the future:

<img width="1046" alt="screen shot 2018-02-21 at 1 40 50 pm" src="https://user-images.githubusercontent.com/52581/36457040-db6ac654-170c-11e8-9c02-ddf01400bba1.png">

**Comment by amdrew** [comment]
An affiliate with no store credit:

<img width="476" alt="screen shot 2018-02-21 at 1 47 19 pm" src="https://user-images.githubusercontent.com/52581/36457219-c8d49b72-170d-11e8-8d7d-ed86b446ef0b.png">

**Comment by amdrew** [comment]
Initial `Store Credit` column on affiliates screen:

<img width="388" alt="screen shot 2018-02-21 at 2 13 04 pm" src="https://user-images.githubusercontent.com/52581/36457944-5e0d79c2-1711-11e8-9e50-9530bc76c59b.png">

Will need to make the sortable and perhaps move it to a better location.

**Comment by amdrew** [comment]
Column now sites between unpaid earnings and the rate:

<img width="391" alt="screen shot 2018-02-21 at 2 49 57 pm" src="https://user-images.githubusercontent.com/52581/36459016-9168bb7e-1716-11e8-8a15-e5834548680a.png">

**Comment by gspice** [comment]
@amdrew Regarding the argument of `affiliate` for the new shortcode, I agree - I do not see a use for it at this time.  The only thing that comes to mind is a leaderboard-esque type list of all affiliate's shortcode balances, but no reason to put that on the frontend when admins can view it on the affiliate list. 

* Tested adding more payouts with store credit enabled, the store credit balance is updated as expected.
* Love the idea of placing the shortcode anywhere on the sit.  Can wrap it with the `[affiliate_content]` shortcode if outside of the affiliate area.
* Like the location of the column on the admin page, will definitely want it sortable. 
* Regarding the store credit balance showing on the edit affiliate screen -- can you add a reset button that takes it to zero?  That is a question we've gotten more than once in support, how to clear out an affiliate's store credit balance.   Some won't be comfortable sending them to the database level to accomplish this.

**Comment by amdrew** [comment]
@gspice That's an interesting idea, can you add that last one as a new issue?

**Comment by michaelbeil** [comment]
Looks great!

As noted in https://github.com/AffiliateWP/affiliatewp-store-credit/issues/10#issuecomment-366872255:
![screen shot on 2018-03-01 at 19_15_14](https://user-images.githubusercontent.com/4752949/36861726-0bd8edec-1d85-11e8-85f4-50e646da73cc.png)

Store credit balance is updated correctly.

I am not seeing Store Credit column on affiliates screen. Any ideas why this may be? I am on `issue/10`.

**Comment by amdrew** [comment]
> I am not seeing Store Credit column on affiliates screen. Any ideas why this may be? I am on issue/10.

@michaelbeil Do you see the store credit on the edit affiliate screen?

**Comment by amdrew** [comment]
EDD + EDD wallet is now supported for the screens shown above. If WooCommerce is active alongside EDD + EDD wallet then it will default to the store credit shown from WooCommerce.

@gspice @michaelbeil Care to give this issue one last test with EDD + EDD Wallet? Then I think we're good to go.

**Comment by michaelbeil** [comment]
I just tested with EDD + EDD wallet and store credit shows on the affiliate area just fine! Bravo! Affiliate screen shows store cedit too.

**Comment by amdrew** [comment]
@michaelbeil Are you still having an issue with not seeing the Store Credit on the affiliates screen in WooCommerce? Did you determine if you were on the correct branch or not?

**Comment by gspice** [comment]
@amdrew 

Everything checked out:
* EDD Wallet displays and kept track of the credit balance correctly in the admin and the affiliate area.
* Installed WooCommerce on the same site, it correctly showed only the WC store credit balance, would not show any credit available in checkout from the previous EDD credits earned, so it was working correctly.

**Comment by amdrew** [comment]
Merged

**Comment by michaelbeil** [comment]
I am seeing the Store Credit column on the affiliates screen.
