### ISSUE TITLE
Add indicator to see what referrals should be paid in Store Credit

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/affiliatewp-store-credit#101]
First requested on this HS ticket:
https://secure.helpscout.net/conversation/840756177/119231?folderId=1170842

Request is to have some sort of indicator (my interpretation anyway) when paying referrals that the affiliate has opted in for Store Credit.   From the ticket text:

>I also wondered how that was tracked when I paid affiliates, if I allow the affiliates to enable store credit, how do I know which ones to pay cash to, and which ones have enabled store credit, so they don't get paid until they place an order?

>When I export the payment report, are the affiliates with store credit not shown in the report?

> I don't want to be paying them in cash and store credit.

**Comment by tjackson1317** [comment]
This lifetime customer is using PayPal Payouts and the Store Credit opt-in feature. He has no way to determine who should get paid via store credit and who should be paid via PayPal when processing a payout. For now, he'll need to check the _Affiliates > Affiliates_ screen to see who has a store credit balance and skip their referrals when doing a PayPal payout. A store credit indicator on the Referrals screen could be helpful, but he's specifically looking for some type of automated filter:

> To pay affiliates as store credit we do a manual payout and mark as paid.
But how can we filter the customers who want to be paid as store credit
against the customers who haven't opted in for store credit and want to be
paid by PayPal?

https://secure.helpscout.net/conversation/1329217097/169612?folderId=205529

**Comment by tjackson1317** [comment]
This customer is also looking to somehow identify or separate referrals that should be paid in store credit from referrals that should be paid in cash:

> so to give the affiliate store credit i will have to mark the referral as "Paid" and it will be as "Paid Earnings" in the Statistics Tab.
> 
> so if the affiliate wants to get paid via PayPal or Bank Transfer .. what do i do ?
> i leave the Referral as " Unpaid " so he doesn't have a store credit or what ? because if i did that it will be as "Unpaid Earnings" and i don't know if this is correct or not , because how will i know if i paid the affiliate the earnings or not

https://secure.helpscout.net/conversation/1333348064/169952?folderId=3962735

**Comment by DrewAPicture** [comment]
Added to the Issues Blitz project and milestoned for v2.3.4.

**Comment by dbeja** [comment]
I just created a PR for this issue: #121 

I also have one question about the scope of this issue: (@DrewAPicture, @tjackson1317, @gspice )
Besides the Store Credit indicator on the list of referrals (#121), should I also implement here some sort of automated filter to make the payment process easier?

**Comment by DrewAPicture** [comment]
> Besides the Store Credit indicator on the list of referrals (#121), should I also implement here some sort of automated filter to make the payment process easier?

No, we'll leave the automated filter for a separate task. Thanks for asking for clarification!

**Comment by dbeja** [comment]
Merged #121 against issue/101.
