### ISSUE TITLE
Adjust how used coupon codes are retrieved in WooCommerce 3.7+

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-store-credit#112]
Just as we did in https://github.com/AffiliateWP/AffiliateWP/issues/3087, we also need to update our WooCommerce integration in Store Credit as a [customer reported](https://secure.helpscout.net/conversation/1193168647/157171?folderId=205527):
>You have usage of function get_used_coupons() for Woocomerce which is deprecated.

>Use WC_Abstract_Order::get_coupon_codes instead.
>Deprecated in version 3.7.

>Could you please check. 
<img width="442" alt="Capture" src="https://user-images.githubusercontent.com/4752949/84544893-85855580-acfe-11ea-97d5-21d2a9e19534.PNG">

The screenshot is referencing the following lines:
https://github.com/AffiliateWP/affiliatewp-store-credit/blob/c31a746cca7ddff050ada2fadd8ce80dc4a7b461/integrations/class-woocommerce.php#L326
https://github.com/AffiliateWP/affiliatewp-store-credit/blob/c31a746cca7ddff050ada2fadd8ce80dc4a7b461/integrations/class-woocommerce.php#L470

**Comment by amdrew** [comment]
Ran into this also. 

> The get_used_coupons function is deprecated since version 3.7. Replace with WC_Abstract_Order::get_coupon_codes.

To replicate, purchase something at checkout with the latest version of WooCommerce, while tracking an affiliate with store credit enabled.

**Comment by DrewAPicture** [comment]
I was just having a bit of deja vu because we _just_ fixed this same issue in ODFA recently. See https://github.com/AffiliateWP/affiliatewp-order-details-for-affiliates/issues/64

**Comment by DrewAPicture** [comment]
@tubiz Would you mind creating a similar PR here to the one we just merged against ODFA?

**Comment by tubiz** [comment]
PR: #123

**Comment by DrewAPicture** [comment]
Merged #123 against `release/2.3.4`
