### ISSUE TITLE
Store credit cannot be used more than once on the same day

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/affiliatewp-store-credit#16]
Customer ticket
https://secure.helpscout.net/conversation/156258210/24419/?folderId=205524

If an affiliate has store credit that is greater than the product total, they can purchase a product and it correctly reduces the `affwp_wc_credit_balance` metakey.

However, if the affiliate then adds another product to the checkout on the same day and applies the credit, the coupon cannot be used, even though there is store credit remaining. 

This looks to be because a new coupon is created with the exact same coupon name as the one before (created based on date and user ID). And since the name is the same, WooCommerce thinks the usage limit has already been reached (1/1).

**Comment by wordmaid** [comment]
Bumping this one - a customer has followed up on it: ref - https://secure.helpscout.net/conversation/156258210/24419/
