### ISSUE TITLE
Allow affiliates to choose preferred payment method

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-store-credit#17]
It may be great to allow affiliates choose their preferred payment method.

**Comment by michaelbeil** [comment]
Related to #3.

**Comment by sumobi** [comment]
https://secure.helpscout.net/conversation/174725823/28577/?folderId=205529

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/224215869/37606/?folderId=205529

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/234479886/39312/?folderId=634609

**Comment by sumobi** [comment]
https://secure.helpscout.net/conversation/328770349/54519/?folderId=205524

**Comment by sumobi** [comment]
https://secure.helpscout.net/conversation/328738110/54513/?folderId=205531

**Comment by gspice** [comment]
Another request:
https://secure.helpscout.net/conversation/343512422/56634/?folderId=205524

**Comment by gspice** [comment]
https://secure.helpscout.net/conversation/379951185/60900/?folderId=205529

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/444522902/68044?folderId=634609

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/444522902/68044?folderId=634609

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/221967641/37256?folderId=634609

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/231105414/38763?folderId=634609

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/594995918/83544/

**Comment by michaelbeil** [comment]
I'm unable to enable/disable the store credit payment method from the affiliate profile settings with the **Enable For All Affiliates?** option disabled and the **Affiliate Enable Store Credit** option enabled.

Any suggestions?

Also, there are some typos we could clean up:
>Affiliate Enable Store Credit

could be 

>Enable Store Credit **per Affiliate** 

This line could be:
>Check this box to allow affiliates **to** enable payout via store credit from their affiliate dashboard.

**Comment by tubiz** [comment]
@michaelbeil, you need to comment out L68 `affiliate_wp()->settings->set( array( 'store-credit-all-affiliates' => '1' ), true );` the upgrade routine is automatically enabling the `Enable For All Affiliates` checkbox.

https://github.com/AffiliateWP/affiliatewp-store-credit/blob/4eff1bc96a1587b9df17d7e5bf5077c558892b12/includes/admin/class-upgrades.php#L64-L74

I will update the PR to fix the typo.

**Comment by michaelbeil** [comment]
Got it!

After doing that, I now see an option to enable payout via store credit from my affiliate dashboard: 
![screen shot on 2018-07-28 at 15_38_19](https://user-images.githubusercontent.com/4752949/43357073-5b575e50-927c-11e8-9d92-07d34001b9fb.png)
