### ISSUE TITLE
Store credit not working if you mark referral as "paid" from add new referral page

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/affiliatewp-store-credit#20]
If you add a new referral manually for an affiliate in the admin, but set the status to `paid` the store credit doesn't get assigned to the affiliate. Only works when you set to unpaid first, then set it to paid.

**Comment by michaelbeil** [comment]
Related to #1.

**Comment by ramiabraham** [comment]
Punting to 2.2, as it needs further debugging and we want to get the other stuff out.

**Comment by gspice** [comment]
Could be related to  https://github.com/AffiliateWP/AffiliateWP/issues/460 since the manual entry with the status set to **Paid** is not populating the payouts

**Comment by DrewAPicture** [comment]
This is probably fixed as of 2.0.10. via [AffiliateWP/AffiliateWP#2257](https://github.com/AffiliateWP/AffiliateWP/issues/2257).

**Comment by amdrew** [comment]
This is working fine now, closing.
