### ISSUE TITLE
Store credit is not edited when referral amount is edited

### ISSUE THREAD

**Issue by simonlk** [AffiliateWP/affiliatewp-store-credit#21]
When a referral is edited, the store credit balance does not change.

If the edited referral is set to unpaid, then the edited referral amount is then taken off the store credit balance. 

Here's a screenshare showing the bug: https://www.screenmailer.com/v/8mCf9Vtuq1aaaPc

**Comment by ramiabraham** [comment]
Punting to 2.2 along with #20

**Comment by ramiabraham** [comment]
Just had an idea on this. So far, we've been debugging timing against the `affwp_process_update_referral` action to concurrently get the old and new values. 

A different approach may be to add a filter to the store credit method that needs this data, and then pass the data from `affwp_process_update_referral`, from core --> add-on.

The downside of _this_ approach is that we'll need to make some small changes to `affwp_process_update_referral()`.

I am committed to not _JavaScripting our way out of this_ :)

**Comment by pippinsplugins** [comment]
Let's make changes to core to make this easy. It should _not_ be a difficult problem. The fact that it is difficult clearly shows we need an adjustment to core.

**Comment by amdrew** [comment]
In AffiliateWP 1.9 we disabled the amount field for referrals that are already paid. It won't be possible to do what is needed in this issue.
https://github.com/AffiliateWP/AffiliateWP/issues/471#issuecomment-240597764

<img width="882" alt="screen shot 2018-02-22 at 3 34 42 pm" src="https://user-images.githubusercontent.com/52581/36517133-fc29a7f0-17e5-11e8-877d-3a6a150808dd.png">
