### ISSUE TITLE
Recurring transaction support

### ISSUE THREAD

**Issue by ramiabraham** [AffiliateWP/affiliatewp-store-credit#38]
- Recurring transaction support (WooCommerce Subscriptions, RCP, EDD? Would depend on subscription method).
- Automated recurring transaction balance deduction using store credit balance
- Would only be compatible with subscription systems that initiate single transactions for each instance of the subscription period (instead of creating one subscription via the payment gateway during the initial transaction).
- _request: https://secure.helpscout.net/conversation/290571527/49014/?folderId=205529_

**Comment by pippinsplugins** [comment]
Sweet idea.

**Comment by gspice** [comment]
Similar request on this ticket, wants store credit to pay off a "store bill" on recurring payments. 

https://secure.helpscout.net/conversation/345960147/56990/?folderId=205529

**Comment by gspice** [comment]
Another request for this....has woo subscriptions that charge every 4 weeks.  Wants affiliates to have their referral commissions applied to their subscription payments automatically.

https://secure.helpscout.net/conversation/421939250/65620/?folderId=205529

**Comment by michaelbeil** [comment]
I just tested this on the latest, and a referral is generated on a subscription payment that was first referred by an affiliate.

**Comment by tubiz** [comment]
PR: #80 

For now this only works with WooCommerce Subscriptions. 

A settings option was added to be able to enable/disable the feature 

<img width="1067" alt="screenshot at jul 29 11-02-20" src="https://user-images.githubusercontent.com/602184/43365096-0f8af682-931f-11e8-8797-b516cf990b9d.png">

**Comment by michaelbeil** [comment]
Store credit balance is automatically applied to WooCommerce Subscription renewal orders with this PR:
![screen shot on 2018-07-29 at 13_45_56](https://user-images.githubusercontent.com/4752949/43365996-1c671ab8-9336-11e8-818a-5a71a0e734b2.png)

**Comment by pippinsplugins** [comment]
Merged!

**Comment by gspice** [comment]
Forced a renewal to a subscription and it applied my store credit coupon without me having to do anything, his functionality is impressive @tubiz !
