### ISSUE TITLE
Show spent credit and remaining credit balance

### ISSUE THREAD

**Issue by lisag** [AffiliateWP/affiliatewp-store-credit#39]
A customer has asked for an easy way to view an affiliate's spent credit and remaining credit balance. It would also be great for the affiliate to be able to see this in the Affiliate Area.

Ticket ref: https://secure.helpscout.net/conversation/300064976/50190/?folderId=205524

**Comment by sumobi** [comment]
related: https://github.com/AffiliateWP/affiliatewp-store-credit/issues/10

**Comment by amdrew** [comment]
Closing in favor of #10
