### ISSUE TITLE
Easy Digital Downloads Compatibility?

### ISSUE THREAD

**Issue by BlazenWeb** [affiliatewp/AffiliateWP-Store-Credit#4]
Hi I saw that you were planning to make this compatible with Easy Digital Downloads - just wondering if this work has started yet?

Thanks

PS. trying to see where to label this a question rather than issue, sorry

**Comment by sumobi** [comment]
Hi @BlazenWeb,

Sorry, development for EDD hasn't started yet.

**Comment by pippinsplugins** [comment]
Done! https://github.com/affiliatewp/AffiliateWP-Store-Credit/pull/12
