### ISSUE TITLE
Clean-up and bailing on empty statuses in payout processing

### ISSUE THREAD

**Issue by ramiabraham** [AffiliateWP/affiliatewp-store-credit#40]
The associated PR updates WooCommerce Store Credit integration with some checks and bails, particularly in reference to the support request noted below. While this could not be replicated by me, the method _should_ bail if either the _old_ or _new_ referral status can't be determined.

https://secure.helpscout.net/conversation/343635258/56648/?folderId=205527

**Comment by ramiabraham** [comment]
@AffiliateWP/core Added a PR: https://github.com/AffiliateWP/affiliatewp-store-credit/pull/41. I couldn't for the life of me replicate this locally, but added various steps and bails to prevent this issue from occurring. Would love a second opinion here, or if anyone has time to try to replicate it as well, steps on how to replicate.

Presently, one customer (so far) gets a missing args error for the method `AffiliateWP_Store_Credit_Base::process_payout()`. The only active integration is WooCommerce (they're still at WC `2.6.x`):

```php
Warning: Missing argument 2 for AffiliateWP_Store_Credit_Base::process_payout() in /.../wp-content/plugins/affiliatewp-store-credit/integrations/class-base.php on line 80

Warning: Missing argument 3 for AffiliateWP_Store_Credit_Base::process_payout() in /home/kronicju/public_html/wp-content/plugins/affiliatewp-store-credit/integrations/class-base.php on line 80

Warning: Cannot modify header information - headers already sent by (output started at /.../wp-content/plugins/affiliatewp-store-credit/integrations/class-base.php:80) in /.../wp-includes/pluggable.php on line 1179
```

**Comment by sumobi** [comment]
@ramiabraham I've replicated a fatal error, on the same line as the customer noted, except I'm running WC v3. I'm pretty sure it's the same error, just a different interpretation.

``` php
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function AffiliateWP_Store_Credit_Base::process_payout(), 1 passed in /wp-includes/class-wp-hook.php on line 298 and exactly 3 expected in /wp-content/plugins/affiliatewp-store-credit/integrations/class-base.php:80
```

I'll roll back to WC 2.6 to confirm and then test your PR to see if this is fixed. 

To replicate:

1. AffiliateWP 2.0.5 (latest master), WC (latest 3.0.1), Store credit (2.1.1
2. WooCommerce integration enabled, store credit enabled
3. Edit a referral from the Referrals screen, change status to pending (it was set to paid) and update

**Comment by sumobi** [comment]
Same issue as above with WC 2.6.14, guessing it's my PHP version (7.1.1) reporting the slightly different error.

**Comment by sumobi** [comment]
@ramiabraham I can confirm that the PR fixes the issue on WC 2.6.14 and 3.0.1. Tested with all referral statuses to be sure.

**Comment by ramiabraham** [comment]
@sumobi Awesome!

**Comment by pippinsplugins** [comment]
Good to merge and deploy?
