### ISSUE TITLE
Affiliate receiving error: "Sorry, it seems the coupon "affiliate-credit-xxxxxxx" is not yours - it has now been removed from your order." 

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/affiliatewp-store-credit#44]
**From this ticket:**
https://secure.helpscout.net/conversation/385525769/61579/?folderId=1170842

**Description from ticket:** 
When an affiliate attempts to make a purchase applying their store credit balance, they receive the error:   

>Sorry, it seems the coupon "affiliate-credit-xxxxxxxxxx_xx" is not yours - it has now been removed from your order.

(where the x is the number on the coupon generated)

**To reproduce:**
* Using WooCommerce, enable Store Credit, create a referral for an affiliate either manually or from an order purchase using their affiliate link.  
* Mark the referral as **Paid**
* Log in to the site using the affiliates account
* Put some items in the cart, go to Checkout
* Click to apply the credit balance - (when you do this a coupon is created in WooCommerce attached to that affiliate)
* Abandon the purchase
* Log back in and repeat the process 
* You will see the same balance as available for store credit (which is good)
* Apply to your purchase , a 2nd coupon is created
* When you click to submit the order you will receive the error

I deleted the coupon codes generated during this process, cleared cookies and started fresh but the same process happens - a coupon is created and the affiliate receives the error.  

The only way I was able to process the order:
*  Click apply so the coupon was generated again
* Pause and go edit the coupon in another browser as admin, removing the user restriction in : Usage restriction > Email restrictions   

The above would not be possible on a live site. Looking for ways to "reset" the affiliate regarding store credit for the user.

**Comment by DrewAPicture** [comment]
@gspice This should be fixed in #45. Please give that a test.

**Comment by gspice** [comment]
@DrewAPicture This is working nicely!  I tested with a partial credit use, abandoning a cart and returning and all processed successfully.   Any chance we can get this update out today??
