### ISSUE TITLE
Show store credit balance in the affiliate dashboard

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-store-credit#47]
>Hello, we regularly need to see how much store credit our customers have left, but it seems that the only way to do this is to log in as our customers then navigate to the affiliate area.

>Is there a way we can see this in the backend somewhere? Perhaps within the user's profile? That would be superb

https://secure.helpscout.net/conversation/464106516/70060?folderId=634609

**Comment by amdrew** [comment]
Already issue: https://github.com/AffiliateWP/affiliatewp-store-credit/issues/10
