### ISSUE TITLE
Add translation functionality 

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-store-credit#73]
A user would appreciate translation functionality in this add-on.

Should be add translation functionality?

Ticket: https://secure.helpscout.net/conversation/623661841/86262?folderId=634609.

**Comment by amdrew** [comment]
@michaelbeil Translations can be done via wp.org, direct the customer here: https://translate.wordpress.org/projects/wp-plugins/affiliatewp-store-credit
