### ISSUE TITLE
Fatal error when marking referral as paid

### ISSUE THREAD

**Issue by tubiz** [AffiliateWP/affiliatewp-store-credit#78]
The fatal error below is thrown when marking a referral as paid and the EDD integration is enabled but the EDD Wallet plugin is not active.

`PHP Fatal error:  Call to undefined function edd_wallet() in /Users/tubiz/valet-sites/a/wp-content/plugins/affiliatewp-store-credit/integrations/class-edd.php on line 60
`

**Comment by michaelbeil** [comment]
This PR fixes the fatal error when marking a referral as paid with the EDD integration enabled, but the EDD Wallet extension is deactivated.
