### ISSUE TITLE
Update screenshots and documentation for 2.3

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/affiliatewp-store-credit#84]
The [add-on page](https://affiliatewp.com/add-ons/official-free/store-credit/) needs to be updated with new features and screenshots for version 2.3.

Documentation also needs updated: https://docs.affiliatewp.com/category/734-store-credit

**Comment by gspice** [comment]
DONE!  If I missed anything, please let me know.

Setup docs:
https://docs.affiliatewp.com/article/733-store-credit-setup

Download / product page:
https://affiliatewp.com/add-ons/official-free/store-credit/

**Comment by pippinsplugins** [comment]
Looks great!
