### ISSUE TITLE
WooCommerce: Invalid coupon amount and store credit deduction when cart is updated

### ISSUE THREAD

**Issue by tubiz** [AffiliateWP/affiliatewp-store-credit#90]
Invalid coupon amount and store credit deduction when the cart is updated after a coupon has been applied.

#### Issue
- When a coupon is generated and applied for `$60` and a cart item is removed reducing the order total from `$60` to `$40`, the created coupon is still `$60` instead of `$40` 
So `$60` will be deducted from the affiliate store credit balance instead of `$40`

#### Proposed Fix
- Update the fixed cart coupon amount whenever a cart action occurs (add product, remove product, increase quantity, decrease quantity)

First reported on this HS ticket:
https://secure.helpscout.net/conversation/771388156/100085/?folderId=2097895

**Comment by tubiz** [comment]
PR: #93

**Comment by michaelbeil** [comment]
This PR updates the max amount of the affiliate store credit balance based on whether an item is removed from the cart.
