### ISSUE TITLE
WooCommerce: Coupons proliferation and abuse issue

### ISSUE THREAD

**Issue by tubiz** [AffiliateWP/affiliatewp-store-credit#91]
#### Issue
- When a coupon is generated and applied to the cart, after which the coupon is removed, the coupon can still be used later if the coupon code is copied

#### Proposed Fix:
- Delete the generated coupon when it is removed from the cart

First reported on this HS ticket:
https://secure.helpscout.net/conversation/771388156/100085/?folderId=2097895

**Comment by tubiz** [comment]
PR: #92

**Comment by michaelbeil** [comment]
Previous coupon is _not_ able to be used after it is removed from the cart of a previous session with this PR: 
 
![mblro2](https://user-images.githubusercontent.com/4752949/52437201-9cb6a080-2b16-11e9-8d83-ca70b35d1226.png)
