### ISSUE TITLE
Fatal error: Uncaught Exception: Invalid discount coupon

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-store-credit#99]
I have not been able to replicate this error on our testing site, but a customer is experiencing this on their site. We should probably account for this error:

>Fatal error: Uncaught Exception: Invalid discount coupon. in /home/chatbot7/public_html/affiliatewp/wp-content/plugins/woocommerce/includes/data-stores/class-wc-coupon-data-store-cpt.php:107 Stack trace: # 0 / home / chatbot7 / public_html /affiliatewp/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): WC_Coupon_Data_Store_CPT-> read (Object (WC_Coupon)) # 1 / home / chatbot7 / public_html / affiliatewp / wp-content /plugins/woocommerce/includes/class-wc-coupon.php(129): WC_Data_Store-> read (Object (WC_Coupon)) # 2 / home / chatbot7 / public_html / affiliatewp / wp-content / plugins / woocommerce / includes / class -wc-coupon.php (117): WC_Coupon-> read_object_from_database () # 3 /home/chatbot7/public_html/affiliatewp/wp-content/plugins/woocommerce/includes/class-wc-cart.php(1643): WC_Coupon- > __ construct ('affiliate credi ...'/home/chatbot7/public_html/affiliatewp/wp-content/plugins/woocommerce/includes/data-stores/class-wc-coupon-data-store-cpt.php online 107

Ticket: https://secure.helpscout.net/conversation/813591081/103845?folderId=634609.

**Comment by amdrew** [comment]
Another customer is experiencing this also: https://secure.helpscout.net/conversation/815937508/104060/?folderId=205527

The fatal error is triggered when applying store credit to a subscription product (via the WooCommerce Subscriptions extension). Both customers have this extension.

Steps to replicate:

1. Activate latest versions of WooCommerce, WooCommerce Subscriptions and Store Credit
2. Create a subscription product and add to your cart.
3. Proceed to checkout and at the prompt to apply store credit click `Apply`
4. The fatal error occurs

@michaelbeil Can you replicate with the above steps?

@tubiz Could you please look into this when you get a chance?

**Comment by michaelbeil** [comment]
@amdrew Those are the exact same steps that I attempted to replicate the issue, but have not been able to. I just tested this again and I was not able to replicate the issue. The latest versions of WooCommerce, WooCommerce Subscriptions, AffiliateWP, and Store Credit Credit are installed and activated: http://s14890.p27.sites.pressdns.com/wp-admin/plugins.php?plugin_status=active&paged=1&s.

Here is the subscription that I tested it with: http://s14890.p27.sites.pressdns.com/product/subscription/.

![Screen Capture on 2019-04-02 at 11-48-06](https://user-images.githubusercontent.com/4752949/55393306-4fb2e180-553d-11e9-8fbf-3f7de3f7209c.gif)

@tubiz Has been able to replicate this.

**Comment by michaelbeil** [comment]
@tubiz have you been able to work on a fix for this?

**Comment by gspice** [comment]
Customer wrote in again on this issue -- do we have an idea on what this fix might entail?
https://secure.helpscout.net/conversation/815937508/104060?folderId=1170842

**Comment by tubiz** [comment]
I will submit a PR for this today.

**Comment by tubiz** [comment]
PR: #100 

@michaelbeil help test PR.

**Comment by michaelbeil** [comment]
The PR fixes the issue:  
![Screen Capture on 2019-04-13 at 22-40-58](https://user-images.githubusercontent.com/4752949/56085051-5d217300-5e3d-11e9-9d3c-71075c3ac20e.gif)

**Comment by pippinsplugins** [comment]
PR looks good.

@tubiz please go ahead and merge and deploy the update to WordPress.org
